# Generated by Django 3.1.7 on 2021-03-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('photo_location', models.CharField(max_length=60)),
                ('photo_category', models.CharField(max_length=60)),
            ],
        ),
    ]
