# Generated by Django 3.1.7 on 2021-03-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_upload_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photo_category',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photo_location',
            new_name='name',
        ),
    ]
